spring:
  datasource:
    url: jdbc:postgresql://localhost/coolplanet
    username: david
    password: password
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost/coolplanet
    user: david
    password: password
  zipkin:
    enabled: false # Disabling for now, don't want to over-complicate the setup
---
spring:
  datasource:
    url: jdbc:postgresql://db/coolplanet
  flyway:
    url: jdbc:postgresql://db/coolplanet
