version: '3.1'

services:

  db:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=david
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=coolplanet
    ports:
      - "5432:5432"
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  app:
    image: task-processor:0.0.1-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"